[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[build]
target = "xtensa-esp32s3-none-elf"
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  "-C",
  "force-frame-pointers",
]

[unstable]
build-std = ["core"]
